export default {
    index: "/",
    login: "/login",
    signup: "/signup",
    home: "/home",
    dashboard:"/dashboard",
    addtrial:"/trial",
    patient: "/patient",
    addpatient: "/addpatient",
    viewpatient: "/patient/:userId",
    editpatient: "/patient/:userId/edit",
    doctor: "/doctor",
    adddoctor: "/adddoctor",
    viewdoctor: "/doctor/:userId",
    editdoctor: "/doctor/:userId/edit",
    prediction: "/prediction",
    viewprediction: "/prediction/:predictionId",
    addprediction: "/addprediction",
    editprediction: "/prediction/:predictionId/edit",
    diagnosis: "/diagnosis",
    viewdiagnosis: "/diagnosis/:diagnosisId",
    adddiagnosis: "/adddiagnosis",
    editdiagnosis: "/diagnosis/:diagnosisId/edit",
    operation: "/operation",
    viewoperation: "/operation/:operationId",
    addoperation: "/addoperation",
    editoperation: "/operation/:operationId/edit",
    checkup: "/checkup",
    viewcheckup: "/checkup/:checkupId",
    addcheckup: "/addcheckup",
    editcheckup: "/checkup/:checkupId/edit",
}
