accesses = {
    "admin": [
        "Admin",
        "Upload",
        "Create Patient",
        "Create Doctor",
        "Update User",
        "Delete User",
        "Get Patient",
        "Get Doctor",
        "Create Prediction",
        "Update Prediction",
        "Delete Prediction",
        "Get Prediction",
        "Create Diagnosis",
        "Update Diagnosis",
        "Delete Diagnosis",
        "Get Diagnosis",
        "Create Operation",
        "Update Operation",
        "Delete Operation",
        "Get Operation",
        "Create CheckUp",
        "Update CheckUp",
        "Delete CheckUp",
        "Get CheckUp",
    ],

    "doctor": [
        "Doctor",
        "Upload",
        "Get Patient",
        "Get Prediction",
        "Create Diagnosis",
        "Get Diagnosis",
        "Create Operation",
        "Get Operation",
        "Create CheckUp",
        "Get CheckUp",
    ],

    "patient": [
        "Patient",
        "Upload",
        "Create Trial",
        "Get Prediction",
    ],
}